### ISSUE TITLE
Problem with saving into NeXus format including metadata

### ISSUE THREAD

**Issue by kutnyakhov** [OpenCOMPES/sed#352]
Somehow I have a problem to use prc.save("*.nxs").
In particular, it complains with e.g.
"The data entry corresponding to /ENTRY[entry]/INSTRUMENT[instrument]/energy_resolution is required and hasn't been supplied by the reader."
Although this information is provided in the JSON file,
but it became a nested JSON file after last changes with #336 changes.

If I am changing file structure from nested
json_data["/ENTRY[entry]/INSTRUMENT[instrument]"]["energy_resolution"]
to simple JSON structure
json_data["/ENTRY[entry]/INSTRUMENT[instrument/energy_resolution"]
then everything is fine.

@rettigl maybe you can help me with this?

**Comment by rettigl** [comment]
This occurred due to a larger change in the nexus definitions with a new version of pynxtools. Indeed, I should have updated the minimum requirements of pynxtools to reflect this change. 
I will setup a corresponding pull-request.
In the meantime, update pynxtools to the latest version, this should solve the issue

**Comment by kutnyakhov** [comment]
Somehow updating to most recent pynxtools didn't solve that issue - same error occurs.

**Comment by rettigl** [comment]
Can you post or send me a minimal reproducible example that triggers this? Which config files and nexus config files are you using? Does Tutorial 3 run without problem?

**Comment by rettigl** [comment]
> With Tutorial 3 I didn't try, but it also doesn't have those nested structures, e.g.

I will have a look at your config file. In deed, the most recent version of Tutorial 3 uses the [/sed/config/NXmpes_config.json](https://github.com/OpenCOMPES/sed/blob/main/sed/config/NXmpes_config.json) config file, which has the new structure:
https://github.com/OpenCOMPES/sed/blob/714fde6eff6bffe17d1dcce306ec81dba2b18f66/sed/config/mpes_example_config.yaml#L312
This should be supported by the most recent versions of pynxtools (>0.0.9). Can you post your version number, and test the example 3?
